sonar.projectKey=padmajan87_resample-feedback-orb
sonar.organization=padmajan87-1
sonar.projectName=resample-feedback-orb

sonar.links.scm=https://github.com/padmajan87/resample-feedback-orb
sonar.host.url=https://sonarcloud.io

sonar.lang.patterns.shell=**/src/scripts/*
sonar.sh.file.suffixes=.sh

sonar.sources=.
sonar.exclusions=LICENSE,NOTICE,.gitignore,**/*.md
sonar.inclusions=**/*.yaml,**/*.yml,**/*.sh,**/Dockerfile*

sonar.docker.activate=true
sonar.lang.patterns.docker=**/default-executor/Dockerfile


sonar.scm.provider=git
sonar.yaml.activate=true

sonar.lang.patterns.secrets=none
sonar.yaml.file.suffixes=.yaml,.yml
sonar.secrets.file.suffixes=yaml,yml,sh

sonar.verbose=true